Documentation:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Enabled: false

NumericLiterals:
  Enabled: false

MethodLength:
  Enabled: false

AllCops:
  Excludes:
    - db/**
    - config/**
    - script/**
