AllCops:
  Excludes:
    - db/**
    - config/**
    - script/**
    - spec/**

CyclomaticComplexity:
  Max: 10

Documentation:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

SignalException:
  Enabled: false
