module ReservedPaths
  def self.non_username_paths
    %w(
      about
      account
      accounts
      activity
      admin
      all
      announcements
      anywhere
      apps
      auth
      badges
      bar
      bars
      blog
      business
      buttons
      careers
      change_password
      checkusername
      chef
      chefs
      city
      claim
      claimed
      contact
      contacts
      dev
      developer
      devices
      direct_messages
      download
      downloads
      eatmorsel
      engineering
      faq
      favorites
      feed
      find_users
      followers
      following
      forgot_password
      friend_request
      friendrequest
      friends
      goodies
      help
      home
      how_it_works
      im_account
      inbox
      invitations
      invite
      jobs
      join
      kitchen
      list
      login
      logo
      logout
      me
      media
      media_signup
      mentions
      message
      messages
      morsel
      morsels
      notifications
      oauth
      password
      password_reset
      passwords
      place
      places
      positions
      post
      press
      privacy
      products
      replies
      reset_password
      restaurant
      restaurants
      rules
      saved_searches
      search
      security
      sent
      settings
      share
      signin
      signup
      similar_to
      sitemap
      statistics
      tag
      team
      tech
      terms
      tos
      translate
      trends
      unsubscribe
      user
      users
      welcome
      who_to_follow
      widgets
    )
  end
end
