module ReservedPaths
  def self.non_username_paths
    %w(
      about
      account
      accounts
      activity
      admin
      all
      announcements
      anywhere
      apps
      auth
      badges
      bar
      blog
      business
      buttons
      change-password
      checkusername
      chef
      city
      claim
      claimed
      contact
      contacts
      devices
      direct-messages
      download
      downloads
      eatmorsel
      faq
      favorites
      feed
      find-users
      followers
      following
      forgot-password
      friend-request
      friendrequest
      friends
      goodies
      help
      home
      how-it-works
      im-account
      inbox
      invitations
      invite
      jobs
      join
      kitchen
      list
      login
      logo
      logout
      me
      media
      media-signup
      mentions
      messages
      morsel
      notifications
      oauth
      password
      password-reset
      passwords
      place
      places
      positions
      post
      press
      privacy
      products
      public-timeline
      replies
      reset-password
      restaurant
      rules
      saved-searches
      search
      security
      sent
      settings
      share
      signin
      signup
      similar-to
      sitemap
      statistics
      tag
      team
      terms
      tos
      translate
      trends
      unsubscribe
      user
      users
      welcome
      who-to-follow
      widgets
    )
  end
end
