developer:
  email: <%= ENV['DEVELOPER_EMAIL'] %>
aws:
  credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  buckets:
    default: <%= ENV['S3_DEFAULT_BUCKET'] %>
new_relic:
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
rollbar:
  access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  endpoint: <%= ENV['ROLLBAR_ENDPOINT'] %>
