developer_email: <%= ENV['DEVELOPER_EMAIL'] %>

morsel:
  api_url: <%= ENV['MORSEL_API_URL'] %>
  support_email_address: <%= ENV['MORSEL_SUPPORT_EMAIL_ADDRESS'] %>
  web_url: <%= ENV['MORSEL_WEB_URL'] %>
  twitter_username: <%= ENV['MORSEL_TWITTER_USERNAME'] %>

pagination_default_count: <%= ENV['PAGINATION_DEFAULT_COUNT'] %>

aws:
  credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  buckets:
    default: <%= ENV['S3_DEFAULT_BUCKET'] %>

bitly:
  access_token: <%= ENV['BITLY_ACCESS_TOKEN'] %>

facebook:
  app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>

foursquare:
  client_id: <%= ENV['FOURSQUARE_CLIENT_ID'] %>
  client_secret: <%= ENV['FOURSQUARE_CLIENT_SECRET'] %>
  api_version: <%= ENV['FOURSQUARE_API_VERSION'] %>

mandrill:
  api_key: <%= ENV['MANDRILL_API_KEY'] %>
  user_name: <%= ENV['MANDRILL_USER_NAME'] %>

new_relic:
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>

rollbar:
  access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  endpoint: <%= ENV['ROLLBAR_ENDPOINT'] %>

twitter:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
