developer:
  email: <%= ENV['DEVELOPER_EMAIL'] %>
morsel:
  web_url: <%= ENV['MORSEL_WEB_URL'] %>
aws:
  credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  buckets:
    default: <%= ENV['S3_DEFAULT_BUCKET'] %>
facebook:
  app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
pagination_default_count: <%= ENV['PAGINATION_DEFAULT_COUNT'] %>
new_relic:
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
rollbar:
  access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  endpoint: <%= ENV['ROLLBAR_ENDPOINT'] %>
twitter:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
